services:
  routing:
    build: .
    image: remnawave-routing:local
    container_name: remnawave-routing
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - remnawave-network

networks:
  remnawave-network:
    name: remnawave-network
    external: true
