services:
  routing-updater:
    build: .
    container_name: remnawave-routing-autoupdate
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - remnawave-network

networks:
  remnawave-network:
    name: remnawave-network
    external: true
